name: deploy

on:
  push:
    branches: [main] # main 分支有 push 时触发

jobs:
  deploy: # 任务名自取
    runs-on: ubuntu-latest # 在什么环境运行任务
    steps:
      - uses: actions/checkout@v2 # 引用actions/checkout这个action，与所在的github仓库同名
        with:
            submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js v16.x # 步骤名自取
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          publish_branch: main	# 发布到哪个branch
          github_token: ${{ secrets.WIN98_DEPLOY_TOKEN }} # secret 名
          # personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }}	发布到其他repo需要提供上面生成的personal access token
          external_repository: evllis/evllis.github.io	# 发布到哪个repo
          user_name: ${{ secrets.Evllis }}
          user_email: ${{ secrets.7284395@qq.com }}
          commit_message: Update vite-win98se project # 部署时的 git 提交信息，自由填写
